services:
  org-db:
    image: postgres:17-alpine
    container_name: organization-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: org_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - org_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  org_postgres_data: