server:
  port: 8081

spring:
  application:
    name: organization-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: jdbc:postgresql://localhost:5433/org_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # We will use 'update' strictly for today to let Spring generate our tables initially.
      # Once we finalize the entities, we will switch this to 'validate' and extract the SQL for Flyway.
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  # We will turn Flyway off temporarily just while we write our Java Entity classes.
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, metrics